### ISSUE TITLE
Render the docgenInfo provided by react-docgen

### ISSUE THREAD

**Issue by chadfawcett** [TwoStoryRobot/storybook-addon-docgen#1]
`react-docgen` provides the parse docgen onto the Component at `Component.__docgenInfo`. This object is being passed to the storybook docs panel. Currently it just converts the object to a string and displays that.

What we want is for it to be nicely formatted with descriptions and a prop types table. See [this repo](https://github.com/gongreg/react-storybook-addon-docgen) for inspiration. The linked package is `MIT` so you could start by just pulling put the `DocPanel` and see how it looks.

https://github.com/TwoStoryRobot/storybook-addon-docgen/blob/a0eb72c678ed6ea4511a009d80014c21114bc302/src/register.js#L38-L43

**Comment by calebissharp** [comment]
I've put something together that seems to be working (#2). Also, sorry it took so long, there was a programming project that I had for school, so I didn't have as much time as I would've liked to work on it.

**Comment by chadfawcett** [comment]
Resolved in #2
