### ISSUE TITLE
description area for rows without a description field are not formatted as a table

### ISSUE THREAD

**Issue by mccullochk** [TwoStoryRobot/storybook-addon-docgen#11]
![image](https://user-images.githubusercontent.com/15054821/38640421-114d1356-3d89-11e8-9e3e-31c7e5f31e47.png)

**Comment by calebissharp** [comment]
It looks like because right now it's generating each row using
```javascript
[
  ...columns
].join('|')
```
Each end of each row will not have the `|`, and the only reason it was working before was because the markdown renderer gave a bit of leeway. It's fixed just by adding a `'|'` to each side of the joined array.

**Comment by calebissharp** [comment]
I've submitted #13 which does this.

**Comment by chadfawcett** [comment]
Resolved in #13

**Comment by mccullochk** [comment]
Thanks @calebissharp 👍
